export { selectValuesFromMenuList } from './src/selectValuesFromMenuList'
export { getMenuListCombinations } from './src/getMenuListCombinations'
export { getDataFromRows } from './src/getDataFromRows'
export { getDataFromRow } from './src/getDataFromRow'
export { selectValues } from './src/selectValues'
